name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.24.0'
      - name: Test
        run: go test -v ./...

      - name: setup eli
        uses: alis-is/setup-eli@v1
      - name: inject version
        run: |
          eli .github/inject-version.lua ${{ github.ref_name }}

      - name: Build linux-amd64
        run: env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o bin/tezpay-linux-amd64

      # build payout-fa
      - name: Build payout-fa linux-amd64
        run: env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o bin/tezpay_payout-fa-linux-amd64 ./extension/official/payout-fa/

      # Build payout-fixer
      - name: Build payout-fixer linux-amd64
        run: env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o bin/tezpay_payout-fixer-linux-amd64 ./extension/official/payout-fixer/

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.4.0
        with:
          file_glob: true
          tag: ${{ github.ref }}
          file: bin/tezpay*
